//
//  SoundPlayer.m
//  musiculesdev
//
//  Created by Dylan on 1/17/09.
//  Copyright 2009 __MyCompanyName__. All rights reserved.
//

#import "SoundPlayer.h"
//#import "Sound.h"

#define FL ((2.0f * 3.14159f) / 44100.0f)
#define FR ((2.0f * 3.14159f) / 44100.0f)


@implementation SoundPlayer

@synthesize sounds;
@synthesize aqData;

static void aqCallBack(void *in, AudioQueueRef q, AudioQueueBufferRef qb) {
	
	static int phaseL = 0;
	static int phaseR = 0;
	
	
	SoundPlayer *data = (__bridge SoundPlayer *)in;
	short *sinBuffer = (short *)qb->mAudioData;
	
	float sampleL = 0.0f;
	float sampleR = 0.0f;
    float amplitude=10000;
    float pitch=4000;
	
	//Sound *s1 = [data.sounds objectAtIndex:0];
	//Sound *s2 = [data.sounds objectAtIndex:1];
	//Sound *s3 = [data.sounds objectAtIndex:2];
	
	
    qb->mAudioDataByteSize = 4 * data.aqData.frameCount; // 1 frame per packet, two shorts per frame = 4 * frames
    for(int i = 0; i < data.aqData.frameCount*2; i+=2) {
        
        
        
        
        
       /* sampleL = (s1.amplitude * sin(s1.pitch * FL * (float)phaseL)) + (s2.isPlaying ? (s2.amplitude * sin(s2.pitch * FL * (float)phaseL)) + (s3.isPlaying ? (s3.amplitude * sin(s3.pitch * FL * (float)phaseL));
                                                                                                                                               sampleR = (s1.amplitude * sin(s1.pitch * FL * (float)phaseL)) + (s2.isPlaying ? (s2.amplitude * sin(s2.pitch * FL * (float)phaseL)) + (s3.isPlaying ? (s3.amplitude * sin(s3.pitch * FL * (float)phaseL));*/
        sampleL = (amplitude * sin(pitch * FL * (float)phaseL));
        sampleR = (amplitude * sin(pitch * FR * (float)phaseR));
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                      short sampleIL = (int)(sampleL * 32767.0f);
                                                                                                                                                                                                                                                                                      short sampleIR = (int)(sampleR * 32767.0f);
                                                                                                                                                                                                                                                                                      sinBuffer[i] = sampleIL;
                                                                                                                                                                                                                                                                                      sinBuffer[i+1] = sampleIR;
                                                                                                                                                                                                                                                                                      phaseL++;
                                                                                                                                                                                                                                                                                      phaseR++;
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      AudioQueueEnqueueBuffer(q, qb, 0, NULL);
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                      -(id)init {
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                          if(self = [super init]) {
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              self.sounds = [[NSMutableArray alloc] init];
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mSampleRate = 44100.0f;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mFormatID = kAudioFormatLinearPCM;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mFormatFlags = kLinearPCMFormatFlagIsSignedInteger | kAudioFormatFlagIsPacked;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mBytesPerPacket = 4;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mFramesPerPacket = 1;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mBytesPerFrame = 4;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mChannelsPerFrame = 2;
                                                                                                                                                                                                                                                                                              aqData.dataFormat.mBitsPerChannel = 16;
                                                                                                                                                                                                                                                                                              aqData.frameCount = 10024;
                                                                                                                                                                                                                                                                                              aqData.bufferByteSize = aqData.frameCount * aqData.dataFormat.mBytesPerFrame;
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              //Sound *s1 = [[Sound alloc] init];
                                                                                                                                                                                                                                                                                              //Sound *s2 = [[Sound alloc] init];
                                                                                                                                                                                                                                                                                              //Sound *s3 = [[Sound alloc] init];
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              //[self.sounds addObject:s1];
                                                                                                                                                                                                                                                                                              //[self.sounds addObject:s2];
                                                                                                                                                                                                                                                                                              //[self.sounds addObject:s3];
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              AudioQueueNewOutput(&aqData.dataFormat, aqCallBack, (__bridge void *)(self), NULL, kCFRunLoopCommonModes, 0, &aqData.queue); // CFRunLoopGetCurrent()
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              for(int i = 0; i < NUM_BUFFERS; i++) {
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                  UInt32 err = AudioQueueAllocateBuffer(aqData.queue, aqData.bufferByteSize, &aqData.buffers[i]);
                                                                                                                                                                                                                                                                                                  if(err) {
                                                                                                                                                                                                                                                                                                      //NSLog(@\"err:%d\n\");
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            aqCallBack((__bridge void *)(self), aqData.queue, aqData.buffers[i]); //prime buffer
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            AudioQueueSetParameter(aqData.queue, kAudioQueueParam_Volume, 1.0f);
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            return self;
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            -(void)start {
                                                                                                                                                                                                                                                                                                                AudioQueueStart(aqData.queue, NULL);
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            -(void)stop {
                                                                                                                                                                                                                                                                                                                AudioQueueStop(aqData.queue, true);
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            -(void)dealloc {
                                                                                                                                                                                                                                                                                                                AudioQueueDispose(aqData.queue, true);
                                                                                                                                                                                                                                                                                                                //[sounds release];
                                                                                                                                                                                                                                                                                                                //[super dealloc];
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            @end